# 1. 프로젝트 기본 설정
spring.application.name=Team_project
server.port=8080
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true

# 2. Database 설정 (Oracle Cloud 연결 유지)
# 기존 HRM DB가 아닌 금융 시스템용 별도 계정이 있다면 username/password를 수정하세요.
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=EDU
spring.datasource.password=EDU
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

# 3. View 설정 (JSP 사용 유지)
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
server.servlet.jsp.init-parameters.development=true


mybatis.type-aliases-package=com.min.edu.dto
mybatis.mapper-locations=classpath:sql/*.xml

mybatis.configuration.map-underscore-to-camel-case=true

# DB 연결 상세 로그 출력
logging.level.org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl=DEBUG
logging.level.com.zaxxer.hikari.HikariConfig=DEBUG
logging.level.com.zaxxer.hikari=TRACE